### ISSUE TITLE
Feature request: Cache busting JS/CSS files

### ISSUE THREAD

**Issue by ajreading** [castlegateit/terminus#1]
It would be great if the Resource class appended a query parameter to the script and style filenames which it enqueues, to ensure they are automatically cache busted. 

Perhaps using filemtime? There may be a small performance hit: http://stackoverflow.com/questions/5850180/cost-of-file-modification-time-checks

**Comment by ajreading** [comment]
Update: filemtime() checks are in place however there are circumstances or occasions when this is not working as expected.

**Comment by johnkhughes** [comment]
This will be fixed in version 2, which I will merge into master when we've done some more testing.
